const DEFAULT_BOOKABLE_VENUES = [
  {
    id: 'bookable-krg-hamilton-park',
    name: 'Hamilton Park tennis courts',
    suburb: 'Pymble',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/36/hamilton-park-tennis-courts',
    venueId: 36,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 3,
  },
  {
    id: 'bookable-krg-st-ives-village-green',
    name: 'St Ives Village Green tennis courts',
    suburb: 'St Ives',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/50/st-ives-village-green-tennis-courts',
    venueId: 50,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 4,
  },
  {
    id: 'bookable-krg-warrimoo-oval',
    name: 'Warrimoo Oval tennis courts',
    suburb: 'St Ives',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/51/warrimoo-oval-tennis-courts',
    venueId: 51,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 3,
  },
  {
    id: 'bookable-krg-loyal-henry-park',
    name: 'Loyal Henry Park tennis courts',
    suburb: 'Roseville',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/53/loyal-henry-park-tennis-courts',
    venueId: 53,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-krg-the-glade-reserve',
    name: 'The Glade Reserve tennis courts',
    suburb: 'Wahroonga',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/12/the-glade-reserve-tennis-courts',
    venueId: 12,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-krg-lindfield-soldiers-memorial-park',
    name: 'Lindfield Soldiers Memorial Park tennis courts',
    suburb: 'Lindfield',
    address: '62 Tryon Road, East Lindfield NSW 2070',
    location: { lat: -33.7693794, lng: 151.1789161 },
    geoSource: 'openstreetmap_address_verified_council_location',
    geoConfidence: 'medium',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    sport: 'tennis',
    officialUrl: 'https://krg.bookable.net.au/venues/8/lindfield-soldiers-memorial-park-tennis-courts',
    venueId: 8,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-krg-allan-small-park',
    name: 'Allan Small Park tennis courts',
    suburb: 'Killara',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/30/allan-small-park-tennis-courts',
    venueId: 30,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 4,
  },
  {
    id: 'bookable-krg-kent-oval',
    name: 'Kent Oval tennis courts',
    suburb: 'North Turramurra',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/38/kent-oval-tennis-courts',
    venueId: 38,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-krg-regimental-park',
    name: 'Regimental Park tennis courts',
    suburb: 'Killara',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/39/regimental-park-tennis-courts',
    venueId: 39,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 5,
  },
  {
    id: 'bookable-krg-richmond-park',
    name: 'Richmond Park tennis courts',
    suburb: 'St Ives',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/40/richmond-park-tennis-courts',
    venueId: 40,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-krg-turramurra-memorial-park',
    name: 'Turramurra Memorial Park tennis courts',
    suburb: 'Turramurra',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/52/turramurra-memorial-park-tennis-courts',
    venueId: 52,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 4,
  },
  {
    id: 'bookable-krg-robert-pymble-park',
    name: 'Robert Pymble Park tennis courts',
    suburb: 'Pymble',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/54/robert-pymble-park-tennis-courts',
    venueId: 54,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 4,
  },
  {
    id: 'bookable-krg-lindfield-community-centre',
    name: 'Lindfield Community Centre tennis courts',
    suburb: 'Lindfield',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/55/lindfield-community-centre-tennis-courts',
    venueId: 55,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-krg-canoon-road-recreation-area',
    name: 'Canoon Road Recreation Area courts',
    suburb: 'South Turramurra',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/43/canoon-road-recreation-area-courts',
    venueId: 43,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 5,
  },
  {
    id: 'bookable-krg-kendall-village-green',
    name: 'Kendall Village Green tennis courts',
    suburb: 'West Pymble',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/37/kendall-village-green-tennis-courts',
    venueId: 37,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-krg-roseville-park',
    name: 'Roseville Park tennis courts',
    suburb: 'Roseville',
    council: 'Ku-ring-gai Council',
    provider: 'bookable',
    officialUrl: 'https://krg.bookable.net.au/venues/44/roseville-park-tennis-courts',
    venueId: 44,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 7,
  },
  {
    id: 'bookable-bayside-aloha-street',
    name: 'Aloha Street Tennis Courts',
    suburb: 'Mascot',
    address: 'Aloha Street, Mascot NSW 2020',
    location: { lat: -33.9260254, lng: 151.1934517 },
    geoSource: 'openstreetmap_road_centroid_verified_address',
    geoConfidence: 'medium',
    council: 'Bayside Council',
    provider: 'bookable',
    sport: 'tennis',
    officialUrl: 'https://bayside.bookable.net.au/venues/40/aloha-street-tennis-courts',
    venueId: 40,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-bayside-bexley',
    name: 'Bexley Tennis Courts',
    suburb: 'Bexley',
    council: 'Bayside Council',
    provider: 'bookable',
    officialUrl: 'https://bayside.bookable.net.au/venues/114/bexley-tennis-courts',
    venueId: 114,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 1,
  },
  {
    id: 'bookable-bayside-scarborough-park',
    name: 'Scarborough Park Tennis Courts',
    suburb: 'Ramsgate',
    council: 'Bayside Council',
    provider: 'bookable',
    officialUrl: 'https://bayside.bookable.net.au/venues/113/scarborough-park-tennis-courts',
    venueId: 113,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 1,
  },
  {
    id: 'bookable-sutherland-blaxland-dr',
    name: 'Blaxland Dr Tennis Courts, Illawong',
    suburb: 'Illawong',
    council: 'Sutherland Shire Council',
    provider: 'bookable',
    officialUrl: 'https://sutherland.bookable.net.au/venues/5/blaxland-dr-tennis-courts-illawong',
    venueId: 5,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 4,
  },
  {
    id: 'bookable-sutherland-bonnet-bay',
    name: 'Bonnet Bay Tennis Courts',
    suburb: 'Bonnet Bay',
    council: 'Sutherland Shire Council',
    provider: 'bookable',
    officialUrl: 'https://sutherland.bookable.net.au/venues/14/bonnet-bay-tennis-courts',
    venueId: 14,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-sutherland-dobell-road',
    name: 'Dobell Road Tennis Courts, Engadine',
    suburb: 'Engadine',
    council: 'Sutherland Shire Council',
    provider: 'bookable',
    officialUrl: 'https://sutherland.bookable.net.au/venues/16/dobell-road-tennis-courts-engadine',
    venueId: 16,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-sutherland-scylla-bay',
    name: 'Scylla Bay Tennis Courts, Como',
    suburb: 'Como',
    council: 'Sutherland Shire Council',
    provider: 'bookable',
    officialUrl: 'https://sutherland.bookable.net.au/venues/22/scylla-bay-tennis-courts-como',
    venueId: 22,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-sutherland-waterfall',
    name: 'Waterfall Tennis Courts',
    suburb: 'Waterfall',
    council: 'Sutherland Shire Council',
    provider: 'bookable',
    officialUrl: 'https://sutherland.bookable.net.au/venues/30/waterfall-tennis-courts',
    venueId: 30,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-sutherland-woronora-heights',
    name: 'Woronora Heights Tennis Courts',
    suburb: 'Woronora Heights',
    council: 'Sutherland Shire Council',
    provider: 'bookable',
    officialUrl: 'https://sutherland.bookable.net.au/venues/33/woronora-heights-tennis-courts',
    venueId: 33,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 1,
  },
  {
    id: 'bookable-sutherland-yala-road',
    name: 'Yala Road Tennis Courts, Bangor',
    suburb: 'Bangor',
    council: 'Sutherland Shire Council',
    provider: 'bookable',
    officialUrl: 'https://sutherland.bookable.net.au/venues/35/yala-road-tennis-courts-bangor',
    venueId: 35,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-sutherland-bundeena',
    name: 'Bundeena Tennis Courts',
    suburb: 'Bundeena',
    council: 'Sutherland Shire Council',
    provider: 'bookable',
    officialUrl: 'https://sutherland.bookable.net.au/venues/136/bundeena-tennis-courts',
    venueId: 136,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 1,
  },
  {
    id: 'bookable-sutherland-seymour-shaw',
    name: 'Seymour Shaw Park Tennis Courts, Miranda',
    suburb: 'Miranda',
    council: 'Sutherland Shire Council',
    provider: 'bookable',
    officialUrl: 'https://sutherland.bookable.net.au/venues/140/seymour-shaw-tennis-courts-miranda',
    venueId: 140,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 8,
  },
  {
    id: 'bookable-georgesriver-quarry-reserve',
    name: 'Quarry Reserve Tennis Courts',
    suburb: 'South Hurstville',
    council: 'Georges River Council',
    provider: 'bookable',
    officialUrl: 'https://georgesriver.bookable.net.au/venues/81/quarry-reserve-tennis-courts',
    venueId: 81,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-blacktown-ropes-crossing',
    name: 'Ropes Crossing Reserve - Tennis Courts',
    suburb: 'Ropes Crossing',
    council: 'Blacktown City Council',
    provider: 'bookable',
    officialUrl: 'https://blacktown.bookable.net.au/venues/170/ropes-crossing-reserve-tennis-courts',
    venueId: 170,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-blacktown-cavanagh-reserve',
    name: 'Cavanagh Reserve',
    suburb: 'Lalor Park',
    council: 'Blacktown City Council',
    provider: 'bookable',
    officialUrl: 'https://blacktown.bookable.net.au/venues/38/cavanagh-reserve',
    venueId: 38,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-blacktown-pearce-reserve',
    name: 'Pearce Reserve',
    suburb: 'Kings Langley',
    council: 'Blacktown City Council',
    provider: 'bookable',
    officialUrl: 'https://blacktown.bookable.net.au/venues/75/pearce-reserve',
    venueId: 75,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 4,
  },
  {
    id: 'bookable-blacktown-glenwood-reserve',
    name: 'Glenwood Reserve',
    suburb: 'Glenwood',
    council: 'Blacktown City Council',
    provider: 'bookable',
    officialUrl: 'https://blacktown.bookable.net.au/venues/49/glenwood-reserve',
    venueId: 49,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'bookable-blacktown-quakers-hill-park',
    name: 'Quakers Hill Park',
    suburb: 'Quakers Hill',
    council: 'Blacktown City Council',
    provider: 'bookable',
    officialUrl: 'https://blacktown.bookable.net.au/venues/80/quakers-hill-park',
    venueId: 80,
    organisationId: 1,
    enabled: true,
    auditCourtCount: 2,
  },
];

export {
  DEFAULT_BOOKABLE_VENUES,
};
