const DEFAULT_SPORTLOGIC_VENUES = Object.freeze([
  {
    id: 'sportlogic-burwood-tennis-courts',
    name: 'Burwood Tennis Courts',
    suburb: 'Burwood',
    address: 'Park Ave, Burwood NSW 2134',
    location: { lat: -33.8739501, lng: 151.1018491 },
    geoSource: 'openstreetmap_road_centroid_verified_address',
    geoConfidence: 'medium',
    provider: 'sportlogic',
    sport: 'tennis',
    officialUrl: 'https://www.tennisvenues.com.au/booking/burwood-tennis-courts',
    clientId: 'burwood-tennis-courts',
    venueId: '1',
    enabled: true,
    auditCourtCount: 2,
  },
  {
    id: 'sportlogic-collaroy-tennis-club',
    name: 'Collaroy Tennis Club',
    suburb: 'Collaroy',
    address: 'Griffith Park, Anzac Avenue, Collaroy NSW 2097',
    location: { lat: -33.73948, lng: 151.303764 },
    geoSource: 'tennisvenues_venue_page',
    geoConfidence: 'high',
    provider: 'sportlogic',
    sport: 'tennis',
    officialUrl: 'https://www.tennisvenues.com.au/booking/collaroy-tc',
    clientId: 'collaroy-tc',
    enabled: true,
    auditCourtCount: 6,
    aliases: ['Long Reef Point tennis', 'Collaroy Beach tennis'],
    settings: ['coastal', 'scenic', 'beach_nearby'],
    surfaces: ['synthetic'],
  },
  {
    id: 'sportlogic-meadowbank-park-tennis-centre',
    name: 'Meadowbank Park Tennis Centre',
    suburb: 'Meadowbank',
    address: 'Constitution Road, Meadowbank Park, Meadowbank NSW 2114',
    location: { lat: -33.815383, lng: 151.083249 },
    geoSource: 'tennisvenues_venue_page',
    geoConfidence: 'high',
    provider: 'sportlogic',
    sport: 'tennis',
    officialUrl: 'https://www.tennisvenues.com.au/booking/meadowbank-park-tc',
    clientId: 'meadowbank-park-tc',
    enabled: true,
    auditCourtCount: 8,
    surfaces: ['clay', 'synthetic'],
  },
  {
    id: 'sportlogic-artarmon-tennis-centre',
    name: 'Artarmon Tennis Centre',
    suburb: 'Artarmon',
    address: 'Cleland Park, Cnr Hampden Rd and Barton Rd, Artarmon NSW 2064',
    location: { lat: -33.81174, lng: 151.18746 },
    geoSource: 'tennisvenues_venue_page',
    geoConfidence: 'high',
    provider: 'sportlogic',
    sport: 'tennis',
    officialUrl: 'https://www.tennisvenues.com.au/booking/artarmon-tennis',
    clientId: 'artarmon-tennis',
    enabled: true,
    auditCourtCount: 6,
    allowPartialCourtIdentity: true,
    surfaces: ['synthetic'],
  },
  {
    id: 'sportlogic-cammeray-tennis-club',
    name: 'Cammeray Tennis Club',
    suburb: 'Cammeray',
    address: 'Cnr Ernest St and Park Ave, Cammeray NSW 2062',
    location: { lat: -33.82771, lng: 151.2172 },
    geoSource: 'tennisvenues_venue_page',
    geoConfidence: 'high',
    provider: 'sportlogic',
    sport: 'tennis',
    officialUrl: 'https://www.tennisvenues.com.au/booking/cammeray-tc',
    clientId: 'cammeray-tc',
    enabled: true,
    auditCourtCount: 4,
    surfaces: ['synthetic'],
  },
  {
    id: 'sportlogic-primrose-park-tennis',
    name: 'Primrose Park Tennis',
    suburb: 'Cremorne',
    address: 'Matora Lane, Cremorne NSW 2090',
    location: { lat: -33.823439, lng: 151.223121 },
    geoSource: 'tennisvenues_venue_page',
    geoConfidence: 'high',
    provider: 'sportlogic',
    sport: 'tennis',
    officialUrl: 'https://www.tennisvenues.com.au/booking/primrose-park-tc',
    clientId: 'primrose-park-tc',
    enabled: true,
    auditCourtCount: 4,
    surfaces: ['synthetic'],
  },
  {
    id: 'sportlogic-mosman-lawn-tennis-club',
    name: 'Mosman Lawn Tennis Club',
    suburb: 'Mosman',
    address: '32 Rosebery Street, Mosman NSW 2088',
    location: { lat: -33.82074, lng: 151.23686 },
    geoSource: 'tennisvenues_venue_page',
    geoConfidence: 'high',
    provider: 'sportlogic',
    sport: 'tennis',
    officialUrl: 'https://www.tennisvenues.com.au/booking/mosman-lawn-tc',
    clientId: 'mosman-lawn-tc',
    enabled: true,
    auditCourtCount: 6,
    surfaces: ['synthetic'],
  },
  {
    id: 'sportlogic-vince-barclay-tennis-academy',
    name: 'Vince Barclay Tennis Academy',
    suburb: 'Marsfield',
    address: 'Cnr Culloden and Talavera Rd, Marsfield NSW 2122',
    location: { lat: -33.76725, lng: 151.11528 },
    geoSource: 'macquarie_university_official_venue_page',
    geoConfidence: 'high',
    provider: 'sportlogic',
    sport: 'tennis',
    officialUrl: 'https://au.racquetvenues.com/booking/vince-barclay-coaching-academy',
    clientId: 'vince-barclay-coaching-academy',
    enabled: true,
    auditCourtCount: 12,
    surfaces: ['clay', 'hard', 'synthetic'],
  },
]);

export {
  DEFAULT_SPORTLOGIC_VENUES,
};
