const DEFAULT_INTRAC_VENUES = Object.freeze([
  {
    id: 'intrac-moore-park-tennis-courts',
    name: 'Moore Park Tennis Courts',
    suburb: 'Moore Park',
    address: 'Cleveland Street, Moore Park NSW 2021',
    location: { lat: -33.8947714, lng: 151.2200913 },
    geoSource: 'openstreetmap_venue_geometry',
    geoConfidence: 'high',
    provider: 'intrac',
    sport: 'tennis',
    officialUrl: 'https://parklands.intrac.com.au/sports/schedule.cfm?location=72',
    locationId: '72',
    enabled: true,
    auditCourtCount: 4,
  },
  {
    id: 'intrac-camperdown-tennis',
    name: 'Camperdown Tennis',
    suburb: 'Camperdown',
    address: '33 Mallett Street, Camperdown NSW 2050',
    location: { lat: -33.8883244, lng: 151.1761332 },
    geoSource: 'openstreetmap_pitch_verified_address',
    geoConfidence: 'high',
    provider: 'intrac',
    sport: 'tennis',
    officialUrl: 'https://camperdowntennis.intrac.com.au/tennis/book.cfm?location=70',
    locationId: '70',
    enabled: true,
    auditCourtCount: 6,
  },
  {
    id: 'intrac-centennial-parklands-sports-centre',
    name: 'Centennial Parklands Sports Centre Courts',
    suburb: 'Moore Park',
    address: 'Corner Anzac Parade and Lang Road, Moore Park NSW 2021',
    location: { lat: -33.89709789, lng: 151.22277325 },
    geoSource: 'public_map_verified_address',
    geoConfidence: 'medium',
    provider: 'intrac',
    sport: 'tennis',
    officialUrl: 'https://parklands.intrac.com.au/sports/schedule.cfm?location=55',
    referer: 'https://parklandssports.com.au/online-court-bookings/',
    locationId: '55',
    enabled: true,
    auditCourtCount: 11,
  },
]);

export {
  DEFAULT_INTRAC_VENUES,
};
